//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGrupos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaseFamilia
    {
        public int IdClaseFamilia { get; set; }
        public string Clase { get; set; }
        public string Familia { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
