//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGrupos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolProfile
    {
        public int IdRolProfile { get; set; }
        public int IdRol { get; set; }
        public int IdProfile { get; set; }
    }
}
